import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

	// But you can create a sidebar manually
	dtcSidebar: [
		'intro',
		'quickstart',
{
			type: 'category',
			label: 'Nodes',
			items: [
				'nodes-overview',
				{
					type: 'category',
					label: 'Source',
					items: [{ type: 'autogenerated', dirName: 'source' }],
				},
				{
					type: 'category',
					label: 'Agents',
					items: [{ type: 'autogenerated', dirName: 'agents' }],
				},
				{
					type: 'category',
					label: 'Audio',
					items: [{ type: 'autogenerated', dirName: 'audio' }],
				},
				{
					type: 'category',
					label: 'Data',
					items: [{ type: 'autogenerated', dirName: 'data' }],
				},
				{
					type: 'category',
					label: 'Database',
					items: [{ type: 'autogenerated', dirName: 'database' }],
				},
				{
					type: 'category',
					label: 'Embedding',
					items: [{ type: 'autogenerated', dirName: 'embedding' }],
				},
				{
					type: 'category',
					label: 'Image',
					items: [{ type: 'autogenerated', dirName: 'image' }],
				},
				{
					type: 'category',
					label: 'Infrastructure',
					items: [{ type: 'autogenerated', dirName: 'infrastructure' }],
				},
				{
					type: 'category',
					label: 'LLM',
					items: [{ type: 'autogenerated', dirName: 'llm' }],
				},
				{
					type: 'category',
					label: 'Memory',
					items: [{ type: 'autogenerated', dirName: 'memory' }],
				},
				{
					type: 'category',
					label: 'Preprocessor',
					items: [{ type: 'autogenerated', dirName: 'preprocessor' }],
				},
				{
					type: 'category',
					label: 'Search',
					items: [{ type: 'autogenerated', dirName: 'search' }],
				},
				{
					type: 'category',
					label: 'Store',
					items: [{ type: 'autogenerated', dirName: 'store' }],
				},
				{
					type: 'category',
					label: 'Text',
					items: [{ type: 'autogenerated', dirName: 'text' }],
				},
				{
					type: 'category',
					label: 'Tool',
					items: [{ type: 'autogenerated', dirName: 'tools' }],
				},
				{
					type: 'category',
					label: 'Video',
					items: [{ type: 'autogenerated', dirName: 'video' }],
				},
			],
		},
		{
			type: 'category',
			label: 'SDK',
			items: [{ type: 'autogenerated', dirName: 'sdk' }],
		},
		{
			type: 'category',
			label: 'MCP Server',
			items: [{ type: 'autogenerated', dirName: 'mcp_server' }],
		},
		{
			type: 'category',
			label: 'API Documentation',
			items: [{ type: 'autogenerated', dirName: 'api' }],
		},
		{
			type: 'category',
			label: 'VS Code Extension',
			items: [{ type: 'autogenerated', dirName: 'vscode-extension' }],
		},
	],
};

export default sidebars;
